Adjustments to User model for domain validation
FAP2024-Turma02/aba-network pull request #23
Opened 2024-09-27 15:59 UTC by Nataly-Carvalho

2024-09-30 16:47 UTC, pablomorato1 commented on app/models/user.rb
> +    allowed_domains = Domain.pluck(:domain_url)
Irei aprovar pois efetivamente não está errado mas precisaremos discutir isso em sala amanhã.

Da forma que está aqui, um usuário poderia se registrar a partir de qualquer dominio existente na plataforma, sem ter como limitar diretamente aos dominios que uma company especifica possui no sistema.

Discutiremos mais sobre o assunto posteriormente.

2024-09-30 16:48 UTC, pablomorato1 approved these changes

2024-09-30 16:50 UTC, pablomorato1 requested changes

2024-09-30 16:50 UTC, pablomorato1 commented on app/models/user.rb
> +      errors.add(:email, "deve ser de um domínio válido (#{allowed_domains.join(', ')})")
Notei isso depois de aprovar.
Não se pode mostrar os dominios que dariam o caso certo, não faz sentido eu ter algo que controla esse fluxo de acesso e caso ele falhe, eu mostre o que "tem que fazer pra dar certo"

2024-09-30 16:53 UTC, Nataly-Carvalho commented on app/models/user.rb
> +      errors.add(:email, "deve ser de um domínio válido (#{allowed_domains.join(', ')})")
vou alterar professor

2024-10-01 22:41 UTC, ricomf approved these changes
👨‍💻🚀🎊🎉🥳

2024-10-02 23:24 UTC, pablomorato1 approved these changes

2024-10-02 23:37 UTC, merged