Add gem pudit
FAP2024-Turma02/aba-network pull request #27
Opened 2024-10-03 13:28 UTC by ricomf

Adicionando a Gem Pundit na Gemfile e Gemfile.lock.

2024-10-03 13:54 UTC, Nataly-Carvalho approved these changes

2024-10-03 14:13 UTC, pablomorato1 requested changes

2024-10-03 14:13 UTC, pablomorato1 commented on app/controllers/application_controller.rb
> +        include Pundit::Authorization
💣

2024-10-07 19:26 UTC, pablomorato1 approved these changes
🥳

2024-10-08 01:11 UTC, merged