update user controller and policy's.
FAP2024-Turma02/aba-network pull request #29
Opened 2024-10-07 14:55 UTC by ricomf

Atualizando controller e policy de user.

2024-10-07 19:30 UTC, pablomorato1 requested changes

2024-10-07 19:30 UTC, pablomorato1 commented on db/seeds.rb
> +Comment.destroy_all
Deve-se haver uma condicional que verifica qual se o ambiente que isso está rodando no ambiente de development apenas.

Imagina um estagiário rodando o `rake db:seeds` em produção

2024-10-07 19:31 UTC, pablomorato1 commented
Este PR só deve ser mergeado após os anteriores (vulgo #27 e #28 )

2024-10-08 00:25 UTC, ricomf commented on db/seeds.rb
> +Comment.destroy_all
Tem razão... vou alterar agora.

2024-10-15 12:56 UTC, pablomorato1 requested changes

2024-10-15 12:56 UTC, pablomorato1 commented on app/policies/user_policy.rb
> +    current_user.admin?  # Apenas administradores podem listar usuários
Acredito que a gente falou sobre isso em sala pra deixar aberto.

2024-10-22 02:20 UTC, pablomorato1 requested changes

2024-10-22 02:20 UTC, pablomorato1 commented on app/controllers/users_controller.rb
> +    @user = User.find(params[:id])
||=

2024-10-22 02:20 UTC, pablomorato1 commented on app/models/user.rb
> +  def admin?
Metodo redundante, o enum do rails já gera uma verificação exatamente igual

2024-10-22 02:20 UTC, pablomorato1 commented on app/policies/user_policy.rb
> +    current_user.admin? || current_user == user  # Admins ou o próprio usuário podem ver seus dados
Se a index é aberta, porquê o show não seria?

2024-10-22 14:27 UTC, Nataly-Carvalho approved these changes

2024-10-23 22:32 UTC, pablomorato1 submitted a review, later dismissed
🥳

2024-10-28 22:04 UTC, pablomorato1 approved these changes
Aprovei mas deixei pontos de melhoria para prestar atenção

2024-10-28 22:04 UTC, pablomorato1 commented on app/controllers/users_controller.rb
> +  before_action :set_user, only: [:show]
Desnecessauro

2024-10-28 22:04 UTC, pablomorato1 commented on app/controllers/users_controller.rb
> +    authorize @user  # Autoriza a exibição de um único usuário
`authorize user`

Sempre chame o método ao invés da variável quando o método é o responsável por instanciar a mesma

2024-10-28 22:04 UTC, pablomorato1 commented on app/controllers/users_controller.rb
> +    render json: @user
RT no comentário acima

2024-10-28 22:34 UTC, merged