Add create and update to CommentsController
FAP2024-Turma02/aba-network pull request #37
Opened 2024-10-21 11:27 UTC by Nataly-Carvalho

Adiciona as ações `create` e `update` ao `CommentsController` para permitir a criação e atualização de comentários. Também inclui verificação de autorização para garantir que apenas usuários autorizados possam realizar essas ações, com tratamento de erros apropriado caso o usuário não tenha permissão para atualizar um comentário de outro usuário.

2024-10-22 02:29 UTC, pablomorato1 requested changes

2024-10-22 02:29 UTC, pablomorato1 commented on app/controllers/comments_controller.rb
> +    @comment = Comment.new(comment_params)
`Comment.new(permitted_attributes(Comment))`

E na policy de comments vc define os atributos

2024-10-22 02:29 UTC, pablomorato1 commented on app/controllers/comments_controller.rb
> +    if @comment.update(comment_params)
Comment.new(permitted_attributes(Comment))

E na policy de comments vc define os atributos

2024-10-22 02:29 UTC, pablomorato1 commented on app/controllers/comments_controller.rb
> +  rescue Pundit::NotAuthorizedError
Deve haver um tratamento para esse rescue diretamente no application controller, e a mensagem de erro deve usar o I18N para gerir as mensagens de forma padronizada

2024-10-22 02:29 UTC, pablomorato1 commented on app/controllers/comments_controller.rb
> +  def comment_params
Usando o permitted_attributes do pundit não se faz necessário ter esse metodo

2024-10-23 14:27 UTC, Nataly-Carvalho commented on app/controllers/comments_controller.rb
Arquivo alterado

2024-10-23 14:27 UTC, Nataly-Carvalho commented on config/routes.rb
Arquivo alterado

2024-10-23 14:28 UTC, Nataly-Carvalho commented on app/policies/comment_policy.rb
Arquivo alterado

2024-10-23 22:29 UTC, closed without merging